title: e-Notes # The title of the blog
author: Ditikrushna Giri # Your name 
email: ditikrushna.nitt@gmail.com # your email shown in the footer
url: https://ditikrushna.me/eNotes/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
 This web page will contain the notes for the following courses: 
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: avatar.JPG # avatar in about page
  about_you: Curious About What,Why & How About Everything
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github: ditikrushna
    rss: RSS
    # dribbble: 
    facebook: diti.giri
    # flickr:   
    # instagram: 
    linkedin: ditikrushnagiri
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: huangyz0918/moving 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
